#!/usr/bin/zsh

USAGE="$(cat << \
-------------------------------------------------------------------------------
addScriptsRoot

part of Atypical - A Typical Arch Linux Install Script
Ethan Schoonover <es@ethanschoonover.com>


Summary:
addScriptsRoot filepath

Details:
Accepts local relative, local absolute, remote http, https and ftp URIs.

If remote url ends in .git, git cloning is used. If it doesn't end in .git
then curl is used to recursively download the source url.
-------------------------------------------------------------------------------
)"

:<< \
-------------------------------------------------------------------------------
ADDING CUSTOM MANIFEST ROOT
-------------------------------------------------------------------------------
local _load_filepath

:''<<< Checking for local or remote custom manifest root...
_load_filepath=$1

if [[ "$_load_filepath" =~ "(http|ftp)s?:.*" ]]; then
    _temp_dir=$(mktemp -d)
    curl -sL $_load_filepath > $_temp_filepath || return 1
    _load_filepath="$_temp_filepath"
else [[ "${_load_filepath:0:1}" != "/" ]]
    # create absolute path
    _load_filepath="${_load_defaultpath%/}${_load_defaultpath:+/}${_load_filepath}"
fi

if [[ ! -f "$_load_filepath" ]]; then
    print "Could not load file $_load_filepath"
    return 1
fi

if [[ -z ${OPTION[OUTPUT]:-} ]]; then
    . "$_load_filepath"
else
    cat "$_load_filepath"
fi

[[ -z "${_temp_dir:-}" ]] || rm -rf "$_temp_dir"

